name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies with pip
        run: |
<<<<<<< HEAD
          pip install doc8 sphinx sphinx-multiversion
          pip install git+https://github.com/osrf/sphinx-tabs
=======
          pip install --no-warn-script-location --user --upgrade -r requirements.txt
          pip install doc8
>>>>>>> 90525686d2ffcb274b161c805188141f33c0304e

      - run: make html
      - run: doc8 --ignore D001 --ignore-path build
